site_name: Christos Mitsanis
site_description: Personal site for apps, research, protocols, and projects
site_url: https://CMits.github.io/CM_Website
repo_url: https://github.com/CMits/CM_Website

# Your markdown files (about.md, index.md, etc.) are in the repo root
docs_dir: "."

theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - header.autohide
    - toc.follow
    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight
    - announce.dismiss
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CMits
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christos-mitsanis/
    - icon: material/email
      link: mailto:c.mitsanis@uq.edu.au
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Digital_Plants
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@YourTikTokHandle
  announcement:
    type: note
    text: "New! Try my latest Streamlit demo on PSoup → APSIM bridging in the Apps page."

plugins:
  - search
  - awesome-pages
  - blog:
      blog_dir: blog                # blog lives in ./blog
      post_dir: "{blog}/posts"      # posts in ./blog/posts
      archive: true
      categories: true              # auto category pages
      authors_file: "{blog}/.authors.yml"
  - tags

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - assets/styles.css

nav:
  - Home: index.md
  - About: about.md
  - CV: cv.md
  - Apps: apps.md
  - Projects: projects.md
  - Articles: articles.md
  - Presentations: Presentations.md
  - Blog:
      - Blog Home: blog/index.md
