name: Deploy MkDocs site

on:
  push:
    branches: [main]   # or 'master'
  workflow_dispatch:

permissions:
  contents: write   # allow pushing to gh-pages

concurrency:
  group: mkdocs-deploy
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs + Material
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install mkdocs-material pymdown-extensions

      - name: Build (sanity check)
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
