name: Deploy MkDocs site

on:
  push:
    branches: [ main ]   # or 'master'
  workflow_dispatch:

permissions:
  contents: write   # allow pushing to gh-pages

concurrency:
  group: mkdocs-deploy
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed for gh-deploy to reuse the token

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs + Material
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install mkdocs-material pymdown-extensions

      # Optional: fail fast on missing files/links while you’re fixing paths
      - name: Build (strict)
        run: mkdocs build --strict

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # not strictly required, but explicit
        run: |
          mkdocs gh-deploy \
            --force \
            --remote-name origin \
            --branch gh-pages \
            --verbose
